feat:메인화면 컴포넌트 구현
dankookie-4983/4983-client pull request #11
Opened 2023-08-28 03:18 UTC by swb1913

## ✔ 지라 이슈 번호

DAN-12

## 📒 작업 내용

메인화면 컴포넌트를 구현 했습니다. 

## 📢 리뷰어에게 하고 싶은 말
ex) 어디어디를 중점적으로 봐주세요 …

## 📌 PR 전 체크 사항
- [ o] base 브랜치가 **develop** 브랜치로 되어있나요?
- [ o ] PR title에 PR Type을 표시해 두었나요? (feat:, fix:, refact: …)

2023-08-28 03:55 UTC, wan2daaa requested changes
첫 PR 축하드립니당 ㅎ
css코드는 아주 깔끔하고 좋네용! 
네이밍 부분이랑 이름 짓는 부분 오타 부분 수정하고
PR 리뷰 전 `next build` 로 build 문제없는지 체크하고
하면 좋을 것같아요 ㅎ 수고하셨습니다!

2023-08-28 03:55 UTC, wan2daaa commented on src/components/pages/main/main-check-box/MainCheckBox.style.tsx
> +export const CBox = styled(CheckBoxSvg)`
여기 CBox UNCBox 무슨말인진 알것같은데 
이걸 CheckedBox랑 UncheckedBox 이런식으로하는게 좀더 가독성면에서 더 좋을 것같아!

2023-08-28 03:55 UTC, wan2daaa commented on src/components/pages/main/main-filter-button/MainFilterButton.style.tsx
> +  padding: 0.8rem 1.2rem 0.8rem 1.2rem;
이건 padding: 0.8rem 1.2rem 이렇게 줄일수 있우!

2023-08-28 03:55 UTC, wan2daaa commented on src/components/pages/main/main-filter-button/MainFilterButton.tsx
> +        <div key={index}>
원래 key를 index로 하면 안되는데 이것도 검색해보면 좋을 것같아!

2023-08-28 03:55 UTC, wan2daaa commented on src/components/pages/main/main-fixed-button/MainFixedButton.tsx
> +export default function MainFixedButton() {
여기 import 랑 export 사이에 빈칸 하나띄우기!

그리고 MainFixedButton 보다는 NavigationBar 가 조금더 직관적일 것같아

2023-08-28 03:55 UTC, wan2daaa commented on src/components/pages/main/main-fixed-button/MainFixedButton.style.tsx
> +export const MP = styled(NCMypageSvg)`
MP 대신 MyPage로 쓰는게 나을것같아 축약어는 안좋아 오히려 풀어쓰는게 좋은거야!

2023-08-28 03:55 UTC, wan2daaa commented on src/components/pages/main/main-layout/MainLayout.tsx
> +        <style.KategorieDiv>
CategoryDiv !

2023-08-28 03:55 UTC, wan2daaa commented on src/components/pages/main/main-sell-button/MainSellButton.style.tsx
> +  padding: 2.1rem 1.8rem 2.1rem 1.8rem;
padding: 2.1rem 1.8rem

2023-08-28 03:57 UTC, jkj1230 reviewed
첫 PR 고생하셨습니다!
전체적으로 코드가 깔끔한 것 같네용 ㅎㅎ
네이밍 부분만 조금 수정하면 더 좋은 코드가 될 것 같습니다!

2023-08-28 03:57 UTC, jkj1230 commented on src/components/pages/main/main-fixed-button/MainFixedButton.style.tsx
> +export const Home = styled(HomeSvg)`
아이콘 클릭되었을때 Click-Home.svg 로 바뀌게 추가 부탁드립니다!

2023-08-28 03:57 UTC, jkj1230 commented on src/components/pages/main/main-fixed-button/MainFixedButton.tsx
> +export default function MainFixedButton() {
MainFixedButton 은 components 밑에 common 폴더 생성 후 공통으로 빼주세요!

2023-08-28 03:59 UTC, ldh0921 approved these changes
수고하셨습니다.

2023-08-28 04:12 UTC, swb1913 commented on src/components/pages/main/main-fixed-button/MainFixedButton.tsx
> +export default function MainFixedButton() {
확인 했습니다.

2023-09-01 06:26 UTC, wan2daaa approved these changes
첫 PR 아주 다사다난했고 고생많았습니다 수고하셨습니다 ㅎ

2023-09-01 06:31 UTC, jkj1230 approved these changes
수고하셨습니다!

2023-09-01 06:31 UTC, merged